# Generated by Django 3.1.7 on 2021-04-02 22:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=100, verbose_name='Given Name')),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Name')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Surname')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(default='', max_length=100)),
                ('health_notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Health Notes')),
                ('personal_notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Personal Notes')),
                ('sfu_id', models.IntegerField(blank=True, null=True, verbose_name='SFU ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_education', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Years of Education')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_pref', models.CharField(blank=True, choices=[('P', 'Phone'), ('E', 'Email')], max_length=1, null=True, verbose_name='Contact Preference')),
                ('pref_phone_time', models.CharField(blank=True, choices=[('WDM', 'Weekday Mornings'), ('WDA', 'Weekday Afternoons'), ('WDE', 'Weekday Evenings'), ('WEM', 'Weekend Mornings'), ('WEA', 'Weekend Afternoons'), ('WEE', 'Weekend Evenings'), ('ANY', 'Anytime'), ('DNC', 'Do Not Call')], max_length=3, null=True, verbose_name='Preferred Phone Time')),
            ],
            options={
                'verbose_name': 'Adult',
                'verbose_name_plural': 'Adults',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Assessment Name')),
            ],
            options={
                'ordering': ['assessment_name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment_Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('type', models.CharField(choices=[('Numeric', 'Numeric'), ('Pass/Fail', 'Pass/Fail'), ('Text', 'Text')], max_length=9)),
                ('field_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.assessment')),
            ],
            options={
                'verbose_name': 'Assessment Field',
                'verbose_name_plural': 'Assessment Fields',
            },
        ),
        migrations.CreateModel(
            name='Assessment_Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_ran', to='participant_app.assessment')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participantAdult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participant_app.adult', verbose_name='Adult Participant')),
            ],
            options={
                'verbose_name': 'Assessment Run',
                'verbose_name_plural': 'Assessment Runs',
                'ordering': ['participantAdult', 'participantChild'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=100, verbose_name='Given Name')),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Name')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Surname')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(default='', max_length=100)),
                ('health_notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Health Notes')),
                ('personal_notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Personal Notes')),
                ('gestation_length_weeks', models.SmallIntegerField(blank=True, null=True, verbose_name='Gestation Length (Weeks)')),
                ('was_full_term', models.BooleanField(blank=True, null=True, verbose_name='Was Full Term?')),
                ('birth_weight', models.SmallIntegerField(blank=True, null=True, verbose_name='Birth Weight (Grams)')),
                ('birth_height', models.SmallIntegerField(blank=True, null=True, verbose_name='Birth Height (CM)')),
                ('hx_repeated_ear_infection', models.TextField(blank=True, max_length=1000, null=True, verbose_name='HX of Repeated Ear Infection')),
                ('hereditary_audio_problems', models.BooleanField(verbose_name='Hereditary Audio Problems?')),
                ('hereditary_language_pathologies', models.BooleanField(verbose_name='Hereditary Language Pathologies?')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Experiment Name')),
                ('status', models.CharField(choices=[('prep', 'In Prep'), ('recruiting', 'Actively Recruiting'), ('inactive', 'Inactive')], max_length=10)),
            ],
            options={
                'ordering': ['experiment_name'],
            },
        ),
        migrations.CreateModel(
            name='Experiment_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_section_name', models.CharField(max_length=100)),
                ('section_status', models.CharField(choices=[('prep', 'In Prep'), ('recruiting', 'Actively Recruiting'), ('inactive', 'Inactive')], max_length=10)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.experiment')),
            ],
            options={
                'verbose_name': 'Experiment Section',
                'verbose_name_plural': 'Experiment Sections',
                'ordering': ['experiment_section_name'],
            },
        ),
        migrations.CreateModel(
            name='Experiment_Section_Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('type', models.CharField(choices=[('Numeric', 'Numeric'), ('Pass/Fail', 'Pass/Fail'), ('Text', 'Text')], max_length=9)),
                ('field_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.experiment_section')),
            ],
            options={
                'verbose_name': 'Experiment Section Field',
                'verbose_name_plural': 'Experiment Section Fields',
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='Experiment_Section_Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('experiment_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.experiment_section')),
                ('participantAdult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participant_app.adult', verbose_name='Adult Participant')),
                ('participantChild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participant_app.child', verbose_name='Child Participant')),
            ],
            options={
                'verbose_name': 'Experiment Section Run',
                'verbose_name_plural': 'Experiment Section Runs',
                'ordering': ['experiment_section', 'participantAdult', 'participantChild'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Language Name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['language_name'],
            },
        ),
        migrations.CreateModel(
            name='MusicalSkill',
            fields=[
                ('skill', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Musical Skill',
                'verbose_name_plural': 'Musical Skills',
                'ordering': ['skill'],
            },
        ),
        migrations.CreateModel(
            name='Speaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_native', models.BooleanField(default=False, verbose_name='')),
                ('proficiency', models.CharField(choices=[('Native', 'Native Like'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], default='Basic', max_length=12)),
                ('age_learning_started', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('age_learning_ended', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('lang', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='languagespoken', to='participant_app.language')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='participant_app.adult')),
            ],
            options={
                'verbose_name_plural': 'Speaks',
            },
        ),
        migrations.CreateModel(
            name='MusicalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('Professional', 'Professional'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], default='Basic', max_length=12)),
                ('age_learning_started', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('age_learning_ended', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('experience', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instrument', to='participant_app.musicalskill')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='musician', to='participant_app.adult')),
            ],
            options={
                'verbose_name_plural': 'Musical Experiences',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
                'ordering': ['lab_name'],
            },
        ),
        migrations.CreateModel(
            name='IsParentIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPrimary', models.BooleanField(default=False, verbose_name='Primary Contact')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_family', to='participant_app.family')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='participant_app.adult')),
            ],
            options={
                'verbose_name': 'Is Parent In',
                'verbose_name_plural': 'Are Parents In',
            },
        ),
        migrations.CreateModel(
            name='IsExposedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_exposure', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('child', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='participant_app.child')),
                ('lang', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='participant_app.language')),
            ],
            options={
                'verbose_name': 'Is Exposed To',
                'verbose_name_plural': 'Are Exposed To',
            },
        ),
        migrations.CreateModel(
            name='IsChildIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childin', to='participant_app.child')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_family', to='participant_app.family')),
            ],
            options={
                'verbose_name': 'Is Child In',
                'verbose_name_plural': 'Are Children In',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(through='participant_app.IsChildIn', to='participant_app.Child'),
        ),
        migrations.AddField(
            model_name='family',
            name='parents',
            field=models.ManyToManyField(through='participant_app.IsParentIn', to='participant_app.Adult'),
        ),
        migrations.CreateModel(
            name='Experiment_Section_Run_Field_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
                ('experiment_section_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.experiment_section_field')),
                ('experiment_section_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.experiment_section_run')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.lab'),
        ),
        migrations.AddField(
            model_name='child',
            name='exposed_to',
            field=models.ManyToManyField(default=None, through='participant_app.IsExposedTo', to='participant_app.Language', verbose_name='Languages Exposed To'),
        ),
        migrations.CreateModel(
            name='Assessment_Run_Field_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
                ('assessment_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.assessment_field')),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.assessment_run')),
            ],
            options={
                'verbose_name': 'Assessment Run Field Score',
                'verbose_name_plural': 'Assessment Run Field Scores',
            },
        ),
        migrations.AddField(
            model_name='assessment_run',
            name='participantChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participant_app.child', verbose_name='Child Participant'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_app.lab'),
        ),
        migrations.AddField(
            model_name='adult',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='speaks', through='participant_app.Speaks', to='participant_app.Language'),
        ),
        migrations.AddField(
            model_name='adult',
            name='musical_background',
            field=models.ManyToManyField(blank=True, through='participant_app.MusicalExperience', to='participant_app.MusicalSkill'),
        ),
    ]
